version: 0.2
env:
    variables:
        S3_BUCKET: "newer-s3-bucket"
        BUILD_ENV: "prod"
        FOLDER   : "last-pipeline"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli
  
  build:
    commands:
      - ng build --$BUILD_ENV

  post_build:
    commands:
      - aws s3 sync dist s3://$S3_BUCKET

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes