version: 0.2
env:
    variables:
        
        S3_BUCKET: "arush-testing-angular"
        BUILD_FOLDER: "output"
        BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --$$BUILD_ENV
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET_NAME --delete
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes